from setuptools import setup, find_packages

setup(name='apitest',
      version='1.0',
      description="Practice API Testing",
      author='Nick Cramer',
      author_email='nick_cramer@outlook.com',
      packages=find_packages(),
      zip_safe=False,
      install_requires=[
            "atomicwrites==1.4.1",
            "attrs==23.1.0",
            "certifi==2023.7.22",
            "chardet==5.2.0",
            "charset-normalizer==3.3.0",
            "colorama==0.4.6",
            "idna==2.10",
            "iniconfig==2.0.0",
            "Jinja2==3.1.2",
            "MarkupSafe==2.1.3",
            "more-itertools==10.1.0",
            "moves==0.1",
            "oauthlib==3.2.2",
            "ordereddict==1.1",
            "packaging==23.2",
            "pluggy==0.13.1",
            "py==1.11.0",
            "PyMySQL==0.9.3",
            "pytest==7.0.0",
            "pytest-html==2.1.1",
            "pytest-metadata==3.0.0",
            "requests==2.31.0",
            "requests-oauthlib==1.3.0",
            "setuptools==68.2.2",
            "urllib3==2.0.7",
            "wcwidth==0.2.8",
            "WooCommerce==2.1.1"
      ]
      )